/**
 * @fileoverview gRPC-Web generated client stub for point
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.25.0
// source: point.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as point_pb from './point_pb';


export class PointClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSimulateTrailed = new grpcWeb.MethodDescriptor(
    '/point.Point/SimulateTrailed',
    grpcWeb.MethodType.UNARY,
    point_pb.Nothing,
    point_pb.Nothing,
    (request: point_pb.Nothing) => {
      return request.serializeBinary();
    },
    point_pb.Nothing.deserializeBinary
  );

  simulateTrailed(
    request: point_pb.Nothing,
    metadata: grpcWeb.Metadata | null): Promise<point_pb.Nothing>;

  simulateTrailed(
    request: point_pb.Nothing,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: point_pb.Nothing) => void): grpcWeb.ClientReadableStream<point_pb.Nothing>;

  simulateTrailed(
    request: point_pb.Nothing,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: point_pb.Nothing) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/point.Point/SimulateTrailed',
        request,
        metadata || {},
        this.methodDescriptorSimulateTrailed,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/point.Point/SimulateTrailed',
    request,
    metadata || {},
    this.methodDescriptorSimulateTrailed);
  }

  methodDescriptorSetDegraded = new grpcWeb.MethodDescriptor(
    '/point.Point/SetDegraded',
    grpcWeb.MethodType.UNARY,
    point_pb.PointDegradedMessage,
    point_pb.Nothing,
    (request: point_pb.PointDegradedMessage) => {
      return request.serializeBinary();
    },
    point_pb.Nothing.deserializeBinary
  );

  setDegraded(
    request: point_pb.PointDegradedMessage,
    metadata: grpcWeb.Metadata | null): Promise<point_pb.Nothing>;

  setDegraded(
    request: point_pb.PointDegradedMessage,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: point_pb.Nothing) => void): grpcWeb.ClientReadableStream<point_pb.Nothing>;

  setDegraded(
    request: point_pb.PointDegradedMessage,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: point_pb.Nothing) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/point.Point/SetDegraded',
        request,
        metadata || {},
        this.methodDescriptorSetDegraded,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/point.Point/SetDegraded',
    request,
    metadata || {},
    this.methodDescriptorSetDegraded);
  }

  methodDescriptorFinalizePosition = new grpcWeb.MethodDescriptor(
    '/point.Point/FinalizePosition',
    grpcWeb.MethodType.UNARY,
    point_pb.Nothing,
    point_pb.Nothing,
    (request: point_pb.Nothing) => {
      return request.serializeBinary();
    },
    point_pb.Nothing.deserializeBinary
  );

  finalizePosition(
    request: point_pb.Nothing,
    metadata: grpcWeb.Metadata | null): Promise<point_pb.Nothing>;

  finalizePosition(
    request: point_pb.Nothing,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: point_pb.Nothing) => void): grpcWeb.ClientReadableStream<point_pb.Nothing>;

  finalizePosition(
    request: point_pb.Nothing,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: point_pb.Nothing) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/point.Point/FinalizePosition',
        request,
        metadata || {},
        this.methodDescriptorFinalizePosition,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/point.Point/FinalizePosition',
    request,
    metadata || {},
    this.methodDescriptorFinalizePosition);
  }

  methodDescriptorGetPointPosition = new grpcWeb.MethodDescriptor(
    '/point.Point/GetPointPosition',
    grpcWeb.MethodType.UNARY,
    point_pb.Nothing,
    point_pb.PointPositionMessage,
    (request: point_pb.Nothing) => {
      return request.serializeBinary();
    },
    point_pb.PointPositionMessage.deserializeBinary
  );

  getPointPosition(
    request: point_pb.Nothing,
    metadata: grpcWeb.Metadata | null): Promise<point_pb.PointPositionMessage>;

  getPointPosition(
    request: point_pb.Nothing,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: point_pb.PointPositionMessage) => void): grpcWeb.ClientReadableStream<point_pb.PointPositionMessage>;

  getPointPosition(
    request: point_pb.Nothing,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: point_pb.PointPositionMessage) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/point.Point/GetPointPosition',
        request,
        metadata || {},
        this.methodDescriptorGetPointPosition,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/point.Point/GetPointPosition',
    request,
    metadata || {},
    this.methodDescriptorGetPointPosition);
  }

  methodDescriptorSetPointMachineState = new grpcWeb.MethodDescriptor(
    '/point.Point/SetPointMachineState',
    grpcWeb.MethodType.UNARY,
    point_pb.PointMachineStateMessage,
    point_pb.SetPointMachineStateResponse,
    (request: point_pb.PointMachineStateMessage) => {
      return request.serializeBinary();
    },
    point_pb.SetPointMachineStateResponse.deserializeBinary
  );

  setPointMachineState(
    request: point_pb.PointMachineStateMessage,
    metadata: grpcWeb.Metadata | null): Promise<point_pb.SetPointMachineStateResponse>;

  setPointMachineState(
    request: point_pb.PointMachineStateMessage,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: point_pb.SetPointMachineStateResponse) => void): grpcWeb.ClientReadableStream<point_pb.SetPointMachineStateResponse>;

  setPointMachineState(
    request: point_pb.PointMachineStateMessage,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: point_pb.SetPointMachineStateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/point.Point/SetPointMachineState',
        request,
        metadata || {},
        this.methodDescriptorSetPointMachineState,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/point.Point/SetPointMachineState',
    request,
    metadata || {},
    this.methodDescriptorSetPointMachineState);
  }

  methodDescriptorGetPointMachineState = new grpcWeb.MethodDescriptor(
    '/point.Point/GetPointMachineState',
    grpcWeb.MethodType.UNARY,
    point_pb.Nothing,
    point_pb.PointMachineStateMessage,
    (request: point_pb.Nothing) => {
      return request.serializeBinary();
    },
    point_pb.PointMachineStateMessage.deserializeBinary
  );

  getPointMachineState(
    request: point_pb.Nothing,
    metadata: grpcWeb.Metadata | null): Promise<point_pb.PointMachineStateMessage>;

  getPointMachineState(
    request: point_pb.Nothing,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: point_pb.PointMachineStateMessage) => void): grpcWeb.ClientReadableStream<point_pb.PointMachineStateMessage>;

  getPointMachineState(
    request: point_pb.Nothing,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: point_pb.PointMachineStateMessage) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/point.Point/GetPointMachineState',
        request,
        metadata || {},
        this.methodDescriptorGetPointMachineState,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/point.Point/GetPointMachineState',
    request,
    metadata || {},
    this.methodDescriptorGetPointMachineState);
  }

}

