name: NuGet Package CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Messages
    - name: Build
      run: dotnet pack -c Release --no-restore src/Messages

    - name: Build and push NuGet Package
      run: dotnet nuget push "src/Messages/bin/Release/Messages.1.0.0.nupkg" --source "https://nuget.pkg.github.com/eulynx-live/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
