name: NuGet Package CI - Messages

on:
  push:
    branches:
      - main
      - release/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore src/Messages

      - name: Build
        run: dotnet pack -c Release --version-suffix "${{ github.ref_name }}" --no-restore src/Messages /p:Version=1.0.1-build.${{ github.run_number }}

      - name: Build and push NuGet Package
        run: dotnet nuget push "src/Messages/bin/Release/EulynxLive.Messages.*.nupkg" --api-key ${{ secrets.NUGET_REGISTRY }} --source https://api.nuget.org/v3/index.json
